"""Template-level axial symmetry contracts."""

from .groups import (
    ContinuousRotationGroup,
    CyclicGroup,
    CyclicRotationGroup,
    RotationGroup,
    SO2Group,
    SymmetryGroup,
    axis_angle_rotation_matrices,
    group_angles,
    group_to_dict,
    intersect_groups,
    intersect_rotation_groups,
    parse_rotation_group,
    rotation_group_matrices,
)
from .hypothesis_expander import (
    DEFAULT_SO2_NUM_SAMPLES,
    DEFAULT_SO2_VISUALIZATION_SAMPLES,
    EquivalentPoseSet,
    SymmetryHypothesisExpander,
    equivalent_gt_pose_set,
    equivalent_gt_poses,
    expand_equivalent_poses,
    expand_pose_hypotheses,
    place_fragment_for_hypothesis,
    symmetry_transforms,
    visualization_equivalent_pose_set,
)
from .metadata import (
    SymmetryAxis,
    SymmetryMetadata,
    SymmetryRegion,
    canonical_object_model_id,
    find_symmetry_sidecar,
    load_symmetry_metadata,
    load_template_symmetry,
    object_model_ids_match,
    symmetry_sidecar_candidates,
)
from .region_assignment import (
    RegionPartitionValidation,
    active_regions,
    active_symmetry_regions,
    assign_regions,
    assign_symmetry_regions,
    axial_coordinates,
    effective_group_from_regions,
    effective_groups_from_regions,
    region_indices_from_membership,
    validate_region_partition,
)
from .targets import (
    SymmetryTargets,
    build_fragment_symmetry_targets,
    build_symmetry_targets,
)

__all__ = [
    "ContinuousRotationGroup",
    "CyclicGroup",
    "CyclicRotationGroup",
    "DEFAULT_SO2_NUM_SAMPLES",
    "DEFAULT_SO2_VISUALIZATION_SAMPLES",
    "EquivalentPoseSet",
    "RotationGroup",
    "RegionPartitionValidation",
    "SO2Group",
    "SymmetryAxis",
    "SymmetryHypothesisExpander",
    "SymmetryGroup",
    "SymmetryMetadata",
    "SymmetryRegion",
    "SymmetryTargets",
    "active_regions",
    "active_symmetry_regions",
    "assign_regions",
    "assign_symmetry_regions",
    "axis_angle_rotation_matrices",
    "axial_coordinates",
    "build_symmetry_targets",
    "build_fragment_symmetry_targets",
    "canonical_object_model_id",
    "effective_group_from_regions",
    "effective_groups_from_regions",
    "equivalent_gt_pose_set",
    "equivalent_gt_poses",
    "expand_equivalent_poses",
    "expand_pose_hypotheses",
    "find_symmetry_sidecar",
    "group_angles",
    "group_to_dict",
    "intersect_groups",
    "intersect_rotation_groups",
    "load_symmetry_metadata",
    "load_template_symmetry",
    "object_model_ids_match",
    "parse_rotation_group",
    "place_fragment_for_hypothesis",
    "region_indices_from_membership",
    "rotation_group_matrices",
    "symmetry_sidecar_candidates",
    "symmetry_transforms",
    "validate_region_partition",
    "visualization_equivalent_pose_set",
]
from .pose_conditioned_resolver import (
    PoseConditionedSymmetryResolution,
    PoseConditionedSymmetryResolver,
)

__all__ = [
    "PoseConditionedSymmetryResolution",
    "PoseConditionedSymmetryResolver",
]
