"""Direct pose representation, hypothesis, and metric primitives."""

from .metrics import (
    axis_direction_error_deg,
    axis_direction_error_rad,
    axis_error_deg,
    pose_rotation_error,
    pose_translation_error,
    rotation_error_deg,
    rotation_error_rad,
    so2_pose_errors,
    symmetry_aware_pose_errors,
    transformed_axis_origin,
    translation_error,
)
from .pose_hypotheses import (
    PoseHypotheses,
    PoseHypothesisSet,
    build_pose_hypotheses,
    select_best_pose,
    topk_pose_hypotheses,
)
from .pose_codec import PoseCodec, PoseCodecContext
from .pose_representation import (
    PoseParameters,
    PoseRepresentation,
    compose_pose_matrix,
    compose_transforms,
    invert_pose,
    invert_transform,
    make_transform,
    matrix_to_pose_9d,
    pose_9d_to_matrix,
    split_transform,
    transform_points,
    validate_transform,
)
from .rotation import (
    axis_angle_to_matrix,
    is_rotation_matrix,
    matrix_to_rotation_6d,
    project_to_so3,
    rotation_6d_to_matrix,
    rotation_6d_to_rotation_matrix,
    rotation_geodesic_distance,
    rotation_matrix_to_6d,
    skew_symmetric,
)
from .weighted_procrustes import WeightedProcrustes

__all__ = [
    "PoseHypotheses",
    "PoseHypothesisSet",
    "PoseCodec",
    "PoseCodecContext",
    "PoseParameters",
    "PoseRepresentation",
    "axis_angle_to_matrix",
    "axis_direction_error_deg",
    "axis_direction_error_rad",
    "axis_error_deg",
    "build_pose_hypotheses",
    "compose_pose_matrix",
    "compose_transforms",
    "invert_pose",
    "invert_transform",
    "is_rotation_matrix",
    "make_transform",
    "matrix_to_pose_9d",
    "matrix_to_rotation_6d",
    "pose_9d_to_matrix",
    "pose_rotation_error",
    "pose_translation_error",
    "project_to_so3",
    "rotation_6d_to_matrix",
    "rotation_6d_to_rotation_matrix",
    "rotation_error_deg",
    "rotation_error_rad",
    "rotation_geodesic_distance",
    "rotation_matrix_to_6d",
    "select_best_pose",
    "skew_symmetric",
    "so2_pose_errors",
    "split_transform",
    "symmetry_aware_pose_errors",
    "topk_pose_hypotheses",
    "transform_points",
    "transformed_axis_origin",
    "translation_error",
    "validate_transform",
    "WeightedProcrustes",
]
