"""Small dependency-free ASCII PLY writer with mandatory vertex RGB."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Sequence

import numpy as np
import torch


def _numpy(value: Any, *, dtype: np.dtype[Any]) -> np.ndarray:
    if isinstance(value, torch.Tensor):
        value = value.detach().cpu().numpy()
    return np.asarray(value, dtype=dtype)


def write_colored_ply(
    path: str | Path,
    vertices: Any,
    colors: Any,
    *,
    faces: Any | None = None,
    edges: Any | None = None,
    comments: Sequence[str] | None = None,
) -> Path:
    """Write one ASCII PLY without overwriting an existing artifact."""

    destination = Path(path)
    if destination.exists():
        raise FileExistsError(f"refusing to overwrite existing PLY: {destination}")
    points = _numpy(vertices, dtype=np.dtype("f4"))
    rgb = _numpy(colors, dtype=np.dtype("u1"))
    if points.ndim != 2 or points.shape[1] != 3:
        raise ValueError("vertices must have shape [V,3]")
    if not np.isfinite(points).all():
        raise ValueError("vertices contain NaN/Inf")
    if rgb.shape == (3,):
        rgb = np.broadcast_to(rgb, (len(points), 3)).copy()
    if rgb.shape != (len(points), 3):
        raise ValueError("colors must have shape [V,3] or [3]")
    triangles = (
        np.empty((0, 3), dtype=np.int64)
        if faces is None
        else _numpy(faces, dtype=np.dtype("i8"))
    )
    line_edges = (
        np.empty((0, 2), dtype=np.int64)
        if edges is None
        else _numpy(edges, dtype=np.dtype("i8"))
    )
    if triangles.ndim != 2 or triangles.shape[1] != 3:
        raise ValueError("faces must have shape [F,3]")
    if line_edges.ndim != 2 or line_edges.shape[1] != 2:
        raise ValueError("edges must have shape [E,2]")
    for name, indices in (("faces", triangles), ("edges", line_edges)):
        if indices.size and (indices.min() < 0 or indices.max() >= len(points)):
            raise ValueError(f"{name} contain out-of-range vertex indices")

    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("x", encoding="ascii", newline="\n") as stream:
        stream.write("ply\nformat ascii 1.0\n")
        stream.write("comment generated by symm_template_reg.visualization.ply\n")
        for comment in comments or ():
            clean = str(comment).replace("\n", " ").replace("\r", " ")
            stream.write(f"comment {clean}\n")
        stream.write(f"element vertex {len(points)}\n")
        stream.write("property float x\nproperty float y\nproperty float z\n")
        stream.write("property uchar red\nproperty uchar green\nproperty uchar blue\n")
        if len(triangles):
            stream.write(f"element face {len(triangles)}\n")
            stream.write("property list uchar int vertex_indices\n")
        if len(line_edges):
            stream.write(f"element edge {len(line_edges)}\n")
            stream.write("property int vertex1\nproperty int vertex2\n")
        stream.write("end_header\n")
        for point, color in zip(points, rgb):
            stream.write(
                f"{point[0]:.9g} {point[1]:.9g} {point[2]:.9g} "
                f"{int(color[0])} {int(color[1])} {int(color[2])}\n"
            )
        for face in triangles:
            stream.write(f"3 {int(face[0])} {int(face[1])} {int(face[2])}\n")
        for edge in line_edges:
            stream.write(f"{int(edge[0])} {int(edge[1])}\n")
    return destination


__all__ = ["write_colored_ply"]
